version: '3.8'

services:
  # Nuxt.js client service
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://api:3001
    develop:
      watch:
        # Watch changes in package.json and package-lock.json relative to /app
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        # Watch changes in the frontend directory relative to /app
        - path: ./client
          target: /app
          action: sync

  # Golang backend API service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_URL: postgres://postgres:78953kiron2x@db:5432/kiron2xDB?sslmode=disable
    develop:
      watch:
        # Watch changes in go.mod and go.sum relative to /app
        - path: ./backend/go.mod
          action: rebuild
        - path: ./backend/go.sum
          action: rebuild
        # Watch changes in the backend directory relative to /app
        - path: ./backend
          target: /app
          action: sync

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kiron2xDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 78953kiron2x
    ports:
      - "5432:5432"
    volumes:
      - kiron2x-postgres:/var/lib/postgresql/data

volumes:
  kiron2x-postgres:
