version: '3.8'

services:

  # Nuxt.js client service
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3000
    develop:
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container if there are any changes
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        # it'll watch for changes in the frontend directory and sync the changes with the container real time
        - path: ./client
          target: /app
          action: sync
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.nuxt

  # Golang backend API service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_URL: postgres://postgres:78953kiron2x@host.docker.internal:5432/kiron2xDB?sslmode=disable
    develop:
      watch:
        - path: ./backend/go.mod
          action: rebuild
        - path: ./backend/go.sum
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
    volumes:
      - ./backend:/app

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kiron2xDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 78953kiron2x
    ports:
      - "5432:5432"
    volumes:
      - kiron2x-postgres:/var/lib/postgresql/data

volumes:
  kiron2x-postgres:
