version: '3.8'

services:

  # Nuxt.js client service
  web:
    depends_on:
      - api
    build: ./client
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3000
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.nuxt

  # Golang backend API service
  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_URL: postgres://postgres:78953kiron2x@host.docker.internal:5432/kiron2xDB?sslmode=disable
    volumes:
      - ./backend:/app
    develop:
      watch:
        - path: ./backend/go.mod
          action: rebuild
        - path: ./backend/go.sum
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kiron2xDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 78953kiron2x
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - kiron2x-postgres:/var/lib/postgresql/data

volumes:
  kiron2x-postgres:
    driver: local
