version: '3.8'

services:

  # Nuxt.js client service
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3000
    develop:
      watch:
        - path: /app/**
          action: rebuild
          ignore:
            - node_modules/
    volumes:
      - ./client:/app

  # Golang backend API service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_URL: postgres://postgres:78953kiron2x@host.docker.internal:5432/kiron2xDB?sslmode=disable
    volumes:
      - ./backend:/app
    develop:
      watch:
        - path: /app/**
          action: rebuild

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kiron2xDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 78953kiron2x
    ports:
      - "5432:5432"
    volumes:
      - kiron2x-postgres:/var/lib/postgresql/data

volumes:
  kiron2x-postgres:
    driver: local
